server:
  port: 9090
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
spring:
  application:
    name: registration-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  #  datasource:
#    url:
#    username:
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: registration-service
            client-secret: WIUjWuVtk2I0CPgQS5552AB9LrghIUhG
            scope: openid,roles
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/cms

frontend.url: http://localhost:4200
keycloak:
  admin.baseUrl: http://localhost:8080/admin/realms/cms/users